// Pages Functions middleware — Markdown for Agents content negotiation.
//
// On `Accept: text/markdown` it returns the requested page's pre-built .md
// companion (generated by build.js into each site's dist) with
// `Content-Type: text/markdown`. Otherwise HTML is served unchanged and an
// agent-discovery Link header pointing to /llms.txt is added.
//
// Shared across every site: the logic is generic and the per-site .md files
// + llms.txt live in each deployment's assets. Deployed automatically because
// `wrangler pages deploy <dir>` (run from the repo root by the deploy
// workflows) compiles this repo-root functions/ directory. Defensive — any
// error falls through to next() so a normal HTML response is always served.
const AGENT_LINK = '</llms.txt>; rel="describedby"';

export async function onRequest(context) {
  const { request, next, env } = context;
  try {
    const url = new URL(request.url);
    const accept = request.headers.get('Accept') || '';
    const wantsMarkdown = /\btext\/markdown\b/i.test(accept);

    // Map a document route to its .md companion (skip real file extensions).
    let mdPath = null;
    const p = url.pathname;
    if (p.endsWith('/')) mdPath = p + 'index.md';
    else if (p.endsWith('.html')) mdPath = p.slice(0, -5) + '.md';
    else if (!/\.[a-zA-Z0-9]+$/.test(p)) mdPath = p + '/index.md';

    if (wantsMarkdown && mdPath && env && env.ASSETS) {
      const res = await env.ASSETS.fetch(new Request(new URL(mdPath, url.origin), {
        headers: { Accept: 'text/markdown' },
      }));
      if (res && res.ok) {
        const body = await res.text();
        const headers = new Headers();
        headers.set('content-type', 'text/markdown; charset=utf-8');
        headers.set('x-markdown-tokens', String(Math.ceil(body.length / 4)));
        headers.set('vary', 'Accept');
        headers.set('link', AGENT_LINK);
        return new Response(body, { status: 200, headers });
      }
    }

    const response = await next();
    const ct = response.headers.get('content-type') || '';
    if (ct.includes('text/html')) {
      const r = new Response(response.body, response);
      r.headers.append('Link', AGENT_LINK);
      r.headers.append('Vary', 'Accept');
      return r;
    }
    return response;
  } catch (err) {
    return next();
  }
}
